name: build pdf

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build pdf and upload release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "14"
      - run: npm install
      - name: build pdf
        run: npm run build:pdf
      - name: create release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./docs/README.pdf
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
